#!/usr/bin/env bash

# Only exported variables can be used within the timer's command.
export PRIMARY_DISPLAY="$(xrandr | awk '/ primary/{print $1}')"
export LOCK_CMD="xsecurelock"

# Run xidlehook
xidlehook \
  --not-when-fullscreen \
  --not-when-audio \
  --timer 60 \
    'xrandr --output "$PRIMARY_DISPLAY" --brightness .1' \
    'xrandr --output "$PRIMARY_DISPLAY" --brightness 1' \
  --timer 120 \
    'xrandr --output "$PRIMARY_DISPLAY" --brightness 1; $LOCK_CMD' \
    '' \
  --timer 3600 \
    'systemctl suspend' \
    ''
